name: Auto build image
on:
  issue_comment:
    types:
      - created
jobs:
  issue_comment:
    name: Auto build image
    if: startswith(github.event.comment.body, '/imagebuild')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Check outputs
        id: autobuild
        run: |
          commentbody="${{github.event.comment.body}}"
          tag=`echo "$commentbody"|cut -d" " -f2`
          branch=`echo "$commentbody"|cut -d" " -f3`
          multi_arch=`echo "$commentbody"|cut -d" " -f4`

          echo $tag
          wget https://sealer.oss-cn-beijing.aliyuncs.com/sealer-latest.tar.gz
          sudo tar -xvf sealer-latest.tar.gz -C /usr/bin
          sudo sealer login ${{secrets.PRIVATEWAREHOUSE}}
          sudo apt install git
          git clone https://github.com/AliyunContainerService/ackdistro.git
          cd ackdistro
          git checkout ${branch}
          cd build

          if [ "$multi_arch" == "multiarch" ]
          then
          sudo bash build.sh $tag true
          else
          sudo bash build.sh $tag
          fi

          sudo sealer tag ack-distro:$tag ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:$tag
          sudo sealer push ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:$tag
          echo "::set-output name=version::$tag"
      - name: Auto build image
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Image ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:${{ steps.autobuild.outputs.version }} build successfully!